version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-job-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sd8q7tvppwrt"
s3_prefix = "sam-job-service"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
